[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
vcsc = "vcsc.vcsc_app:main"

[tool.setuptools]
include-package-data=true

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "vcsc"
description = "Overcomplicated tool to capture the output of a capture card or webcam"
version = "1.0.0a2"
authors = [
    {name = "Bye", email = "bye@byecorps.com"}
]
classifiers= [
    "Development Status :: 3 - Alpha",
    "Environment :: X11 Applications :: Qt",
    "Intended Audience :: End Users/Desktop",
    "Natural Language :: English",

    # Supported Python versions
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",

    # Tested operating systems
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: POSIX :: Linux",

    "Topic :: Multimedia :: Video",
    "Topic :: Multimedia :: Video :: Capture",
    "Topic :: Multimedia :: Video :: Display"
]
readme = "README.md"
license = "Zlib"
requires-python = ">=3.10.0"
dependencies = [
    "rich~=15.0",
    "pyside6>=6.11; os_name != 'nt' or (os_name == 'nt' and platform_release > '10')",
    "pyside6>=6.11, < 6.13; os_name == 'nt' and platform_release <= '10'",
]

[project.urls]
Homepage = "https://byespace.net/software/vcsc/"
Repository = "https://shinonome.rocks/bye/VeryComplicatedScreenCapture"

[dependency-groups]
dev = [
    "imageio>=2.37.3",
    "nuitka>=4.1.2",
]

[tool.setuptools.package-data]
vcsc = ["*.ico", "*.svg"]

[tool.setuptools.data-files]
"share/applications" = ["net.byespace.vcsc.desktop"]
"share/icons/hicolor/scaleable/apps" = ["net.byespace.vcsc.svg"]
"share/metainfo" = ["net.byespace.vcsc.metainfo.xml"]
